### ISSUE TITLE
Error when running limelight: Encountered error during conversion: null

### ISSUE THREAD

**Issue by nattzy94** [yeastrc/limelight-import-crux-tide-percolator#1]
Hi Mike,

I am trying to visualise tide-percolator output using Limelight. I ran the following commands as specified in the README on the `pep.xml` file:
```
perl -p -i -e 's/num_tol_term=\"\"/num_tol_term=\"2\"/g' tide-search.target.pep.xml
perl -p -i -e 's/date=\".+?\" /date=\"2020-01-07T17:05:18\" /g' tide-search.target.pep.xml
perl -0777 -p -i -e 's/<\/modification_info>\n<modification_info.+//g' tide-search.target.pep.xml
```

However, when I run limelight with` java -jar /Users/nathaniel/Documents/cruxTide2LimelightXML.jar -d . -f ../../databases/ortho_alltime_translated_no-stops_rmdup_oneline.fa -o teab.limelight.xml -v`, I get the following output:

```
Crux Tide/Percolator to limelight XML converter
Author: Michael Riffle <mriffle@uw.edu>
See: https://github.com/yeastrc/limelight-import-crux-tide-percolator
Version: 1.1.1

Determining location of Crux output files...
	Found pep xml file: /Users/nathaniel/Dropbox/LabResults/NT-029/NT029_proteomics/20210626_analysis-001-trypsin/TEAB.orthoalltime.tide-search.bothscores/./tide-search.target.pep.xml
	Found percolator xml file: /Users/nathaniel/Dropbox/LabResults/NT-029/NT029_proteomics/20210626_analysis-001-trypsin/TEAB.orthoalltime.tide-search.bothscores/./percolator.pout.xml
	Found percolator log file: /Users/nathaniel/Dropbox/LabResults/NT-029/NT029_proteomics/20210626_analysis-001-trypsin/TEAB.orthoalltime.tide-search.bothscores/./percolator.log.txt
	Found tide log file: /Users/nathaniel/Dropbox/LabResults/NT-029/NT029_proteomics/20210626_analysis-001-trypsin/TEAB.orthoalltime.tide-search.bothscores/./percolator.log.txt

Reading Percolator XML data into memory... Found 24186 peptides.
Reading pepXML file...Got an error parsing the pep XML file. Error: null
java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:494)
	at java.math.BigDecimal.<init>(BigDecimal.java:383)
	at java.math.BigDecimal.<init>(BigDecimal.java:806)
	at com.sun.xml.internal.bind.DatatypeConverterImpl._parseDecimal(DatatypeConverterImpl.java:136)
	at com.sun.xml.internal.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$23.parse(RuntimeBuiltinLeafInfoImpl.java:791)
	at com.sun.xml.internal.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$23.parse(RuntimeBuiltinLeafInfoImpl.java:789)
	at com.sun.xml.internal.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.parse(TransducedAccessor.java:230)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:195)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:559)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:357)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:189)
	at org.yeastrc.limelight.xml.tide.utils.TidePepXMLParsingUtils.getMSmsPipelineAnalysis(TidePepXMLParsingUtils.java:176)
	at org.yeastrc.limelight.xml.tide.reader.TidePepXMLResultsParser.getTideResults(TidePepXMLResultsParser.java:50)
	at org.yeastrc.limelight.xml.tide.main.ConverterRunner.convertCruxTidePercolatorToLimelightXML(ConverterRunner.java:72)
	at org.yeastrc.limelight.xml.tide.main.MainProgram.run(MainProgram.java:80)
	at picocli.CommandLine.execute(CommandLine.java:1160)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at picocli.CommandLine.run(CommandLine.java:1974)
	at picocli.CommandLine.run(CommandLine.java:1904)
	at org.yeastrc.limelight.xml.tide.main.MainProgram.main(MainProgram.java:99)
Encountered error during conversion: null
```

The first few lines of my xml file look like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href=""?>
<msms_pipeline_analysis date="2021-07-27T09:58:28" xmlns="http://regis-web.systemsbiology.net/pepXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xs
i:schemaLocation="http://regis-web.systemsbiology.net/pepXML /usr/local/tpp/schema/pepXML_v110.xsd" summary_xml="">
<msms_run_summary base_name="NA" msManufacturer="NA" msModel="NA" msIonization="NA" raw_data_type="NA" raw_data="NA" >
<sample_enzyme name="trypsin">
</sample_enzyme>
<search_summary base_name="NA" search_engine="Crux" precursor_mass_type="monoisotopic" fragment_mass_type="monoisotopic" out_data_type="NA" out_data="NA" sear
ch_id="1" >
<search_database local_path="(null)" type="AA" />
<enzymatic_search_constraint enzyme="trypsin" max_num_internal_cleavages="0" min_number_termini="2"/>
<aminoacid_modification aminoacid="C" mass="160.0307" massdiff="57.02" variable="N" />
<aminoacid_modification aminoacid="A" mass="113.0471" massdiff="42.01" variable="Y" protein_terminus="n" />
<aminoacid_modification aminoacid="C" mass="145.0192" massdiff="42.01" variable="Y" protein_terminus="n" />
<aminoacid_modification aminoacid="D" mass="157.0369" massdiff="42.01" variable="Y" protein_terminus="n" />
<aminoacid_modification aminoacid="E" mass="171.0526" massdiff="42.01" variable="Y" protein_terminus="n" />
```

Any idea how I can resolve this?

Nathaniel

**Comment by mriffle** [comment]
Nathaniel,

This looks like it may be an issue with the pepXML file, itself--possibly missing a required value. Are you able to confidentially share the pepXML with me by some means? I can run it through XML validation software and see what's going on. I'll come up with a fix for the Limelight XML converter and get in touch with the Crux developers about the issue.

Mike

**Comment by mriffle** [comment]
Nathaniel,

There was a couple things going on.

First, the pepXML did contain some invalid values for a field. Run the following command in your crux-output directory to fix the pepXML (in addition to the other commands you already ran):

```
perl -p -i -e 's/mass=\"nan\"/mass=\"0.0\"/g' tide-search.target.pep.xml
```

Second, I found some issues with how Tide rounds numbers when it goes from four to two decimal places when it reports mod masses. I had to update the Limelight XML converter to account for this. I issued a new release (1.1.2) at https://github.com/yeastrc/limelight-import-crux-tide-percolator/releases that should handle the situation.

I tested the pepXML you sent and it was able to parse it correctly.

**Comment by nattzy94** [comment]
Hi Michael,

Thanks for creating a solution so quickly! The converter is running
smoothly now.

Thank you!
